### PR TITLE
Settings page changes

### PR DESCRIPTION
**Pull request by VoitreX**
Just looking at the change log for now

### CODE REVIEW

**Comment by VoitreX** [comment]
Need to Fix tests in Add_Cie, CiE, and Profile!

**Comment by Gleydar** [comment]
I added a default initialisation for the UserSettings in the Session. Might actually not be good form, but I'll think of a nicer version to get default settings for a user thats not logged in soon-ish

**Comment by Gleydar** [comment]
Had to remove some tests, sadly.

**Comment by Gleydar** [comment]
I'm actually stupid and pushed the same changes to here as I did to #150

**Pull request merged**
