### PR TITLE
Cie course tracking

### PR DESCRIPTION
**Pull request by VoitreX**
Added Profile Page, Added CIE course tracking backed in SQL, added tracking of CIE courses, added ability to manually edit this list. Should be good Fingers Crosses. Might need a nasty merge though with others changes.

### CODE REVIEW

**Comment by hmkrivoj** [comment]
Gradle build fails as for now

**Comment by Gleydar** [comment]
Gradle fix should be deployed

**Comment by Gleydar** [comment]
closes #83

**Comment by hmkrivoj** [comment]
Postponed for Sprint3

**Comment by VoitreX** [comment]
This error is due to the database not being filled.

**Comment by VoitreX** [comment]
Made things faster. I don't know if this will break stuff though cause the course provider is all commented out.

**Comment by hmkrivoj** [comment]
Reviewing...

**Comment by VoitreX** [comment]
Need to un-comment the department lookup in cie_screen

**Pull request merged**
