### PR TITLE
Sprint 2 cleanup

### PR DESCRIPTION
**Pull request by Gleydar**
This is the last one, I swear.

### CODE REVIEW

**Comment by Gleydar** [comment]
@BullshitPingu I mean I dont have another one yet, but you can review this one again if u like ;)

**Comment by Gleydar** [comment]
[idea.zip](https://github.com/mobileappdevhm/team2/files/2035191/idea.zip) This file _should_ fix the project - issue is, that .iml Files do not actually belong in the repo, but were tracked from the beginning - when we are ignoring & removing them from git now, git deletes the files, even though we kinda still need them

**Comment by Gleydar** [comment]
instructions - unzip the file and copy contents over the .idea folder in the project - it works fine for me

**Comment by BullshitPingu** [comment]
[team2_android.zip](https://github.com/mobileappdevhm/team2/files/2035215/team2_android.zip)

**Comment by Gleydar** [comment]
the other folder contains the individual .iml file - if the first folder doesn't work, try the second one. just unzip it in the main project directory

**Comment by hmkrivoj** [comment]
I willl merge this one at the end of sprint 1, so nobody get's interrupted by setting their projects up again while working.

**Comment by Gleydar** [comment]
Makes sense to me, added to Sprint 2

**Comment by Gleydar** [comment]
Oh - closing and opening intellij fixes the problem

**Pull request merged**
