### PR TITLE
Timtable upgrade

### PR DESCRIPTION
**Pull request by l0renor**
ICS is correct according to https://icalendar.org/validator.html
but only works on the online Google calendar but not on my phone.

### CODE REVIEW

**Comment by hmkrivoj** [comment]
Trying to resolve conflict, but first pubspec.lock has to disappear

**Comment by hmkrivoj** [comment]
Summoning @VoitreX as the course now contains not a single TimeAndDay but a list of this stuff.
The whole SQLite stuff needs to be adjusted to this thing.

**Comment by VoitreX** [comment]
@hmkrivoj Looking into it now

**Comment by VoitreX** [comment]
Look at my Pull request I think it should help fix this. @l0renor  @hmkrivoj

**Pull request merged**
